[package]
name = "streaming_redirect_server"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
warp = "0.3.7"
tokio = { version = "1", features = ["full"] }