[package]
name = "baby-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "*"
opencv = { version = "*", default-features = false, features = ["imgproc", "imgcodecs", "videoio"]}
tokio = { version = "1.0", features = ["full"] }
