name = "libcamera-vid"
args = [
    "-t",
    "0",
    "--inline",
    "--listen",
    "-o",
    "tcp://0.0.0.0:8081",
    "--width",
    "320",
    "--height",
    "240",
    "--codec",
    "mjpeg",
]
