[[process_list]]
name = "libcamera-vid"
args = [
    "-t",
    "0",
    "--framerate",
    "20",
    "--inline",
    "-o",
    "-",
    "--width",
    "640",
    "--height",
    "480",
    "--codec",
    "mjpeg",
]

[[process_list]]
name = "baby-rs"
args = ["stdin", "--tick", "20"]
